apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#setting namepace
namespace: prod

#setting a name suffix to be appended to each resource name
nameSuffix: -prod

# set base directory as the resource
resources:
- ../../base