apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# setting common annotations for the entire cluster
commonAnnotations:
  a8r.io/owner: "@enibalo"
  a8r.io/repository: "https://github.com/enibalo/vipmed-devops-challenge"

# defining all resource manifests to use to create the cluster
resources:
- user-service.yaml 
- api-gateway.yaml 
- redis.yaml

generatorOptions:
  # annotations to add to all generated resources
  annotations:
    a8r.io/owner: "@enibalo"
    a8r.io/repository: "https://github.com/enibalo/vipmed-devops-challenge"

# create configmaps based on the env files for the user service and api gatway containers  
configMapGenerator:
- name: api-gateway-env
  envs:
  - ./env/api-gateway.env
- name: user-service-env
  envs:
  - ./env/user-service.env

# create a Secret resource based on the secrets.env file
secretGenerator:
- name: user-service-secrets
  envs:
  - ./env/secrets.env
  type: Opaque


replacements: 
# create a replacement to update the ports for each deployment based on the environment variables 
- source:
    kind: ConfigMap
    name: api-gateway-env
    fieldPath: data.port
  targets:
  - select:
      kind: Deployment
      name: api-gateway
    fieldPaths:
      - spec.template.spec.containers.0.ports.0
      - spec.template.spec.containers.0.livenessProbe.httpGet.port
      - spec.template.spec.containers.0.readinessProbe.httpGet.port
    options:
        create: true
  - select:
      kind: Service
      name: api-gateway-service
    fieldPaths:
    - spec.port.0
    - spec.port.0.targetPort
    options:
      create: true
- source:
    kind: ConfigMap
    name: user-service-env
    fieldPath: data.port
  targets:
  - select:
      kind: Deployment
      name: user-service
    fieldPaths:
      - spec.template.spec.containers.0.ports.0
      - spec.template.spec.containers.0.livenessProbe.httpGet.port
      - spec.template.spec.containers.0.readinessProbe.httpGet.port
    options:
        create: true
  - select:
      kind: Service
      name: user-service-service
    fieldPaths:
    - spec.port.0
    - spec.port.0.targetPort
    options:
      create: true



