apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image:  "redis:7-alpine"
        ports:
        - containerPort: 6379 
        resources:
          requests:
            cpu: 2
            memory: 5Gi
          limits:
            cpu: 3
            memory: 10Gi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: 
              - "redis-cli"
              - "ping"
          periodSeconds: 20
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 10
