apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-data 
spec:
  selector:
    matchLabels:
      app: redis 
  serviceName: "redis"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: redis 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: "redis:7-alpine"
        ports:
        - containerPort: 6379  
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: aclfile
          mountPath: /usr/local/etc/redis/users.acl
      volumes:
        - name: aclfile
          secret:
            secretName: redis-aclfile
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
