apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#setting namepace
namespace: dev

# change images to their development versions  
images:
- name: enibalo/user-service:prod
  newName: enibalo/user-service
  newTag: dev
- name: enibalo/api-gateway:prod
  newName: enibalo/api-gateway
  newTag: dev

# set base directory as the resource
resources:
- ../../base
- namespace.yaml


# change env variables that need a different value for development
configMapGenerator:
- name: api-gateway-env
  behavior: merge
  envs:
  - api-gateway.env
- name: user-service-env
  behavior: merge
  envs:
  - user-service.env


patches:
# adjust resource limits and requests for each service's containers
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "124Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
  target: 
    kind: Deployment 
    name: api-gateway|user-service
- patch: |- 
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
  target: 
    kind: StatefulSet 
    name: redis-data

# replace the production entrypoint command with the dev entrypoint command for each express service
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command
      value:
        - npm
    - op: add
      path: /spec/template/spec/containers/0/args
      value:
        - run
        - dev
  target: 
    kind: Deployment 
    name: api-gateway-app|user-service-app

replacements: 
# scale down number of replicas for each service for a  development environment 
- sourceValue: "1"
  targets:
  - select:
      kind: Deployment
      name: user-service|api-service
    fieldPaths:
      - spec.replicas


