# Author - Eni Balogun
# Description - 

name: CI/CD Pipeline 
on: [push]
jobs: 
  lint-and-test: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 


      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Load Environment Fields 
        run: | 
          echo {{secrets.USER_SERVICE_SECRETS}} >> secrets.env 
          mv secrets.env ./k8s/base/env/
          echo {{vars.API_GATEWAY_ENV}} >> api-gateway.env 
          mv api-gateway.env ./k8s/base/env/
          echo {{vars.USER_SERVICE_ENV}} >> user-service.env
          mv user-service.env ./k8s/base/env/
    
      - name: Lint and Test API Gateway Service
        run: |  
          docker compose build api-gateway
          docker run api-gateway npm run lint
          docker run api-gateway npm run test
          
      - name: Lint and Test User Service 
        run: | 
          docker compose build  user-service
          docker run  user-service npm run lint
          docker run -e TEST=true user-service npm run test  
         