# Author - Eni Balogun
# Description - 

name: CI/CD Pipeline 
on: [push]
jobs: 
  lint: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 
      - name: Add Dependencies 
        run: npm ci 
      - name: Lint and Test API Gateway Service
        run: | 
          cd apps/api-gateway
          npm run lint
          npm run test 
      - name: Lint and Test User Service 
        run: | 
          cd ../user-service
          npm run lint 
          npm run test         