# Author - Eni Balogun
# Description - 

name: CI/CD Pipeline 
on: [push]
jobs: 
  lint-and-test: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 
      - name: Lint and Test API Gateway Service
        run: | 
          cd apps/api-gateway
          npm ci 
          npm run lint
          npm run test 
      - name: Lint and Test User Service 
        run: | 
          cd apps/user-service
          npm ci 
          npm run lint 
          npm run test         